"""add tag.group

Revision ID: d725067e22f9
Revises: 9c08d2ecbc31
Create Date: 2022-12-23 21:41:08.821488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d725067e22f9"
down_revision = "9c08d2ecbc31"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tags", sa.Column("group", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tags", "group")
    # ### end Alembic commands ###
