"""add tags and things

Revision ID: e925a726b989
Revises: b2ed7dd418f4
Create Date: 2022-12-22 19:46:53.839003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e925a726b989"
down_revision = "b2ed7dd418f4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mention_tags",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "mentions_for_tags",
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("mention_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mention_id"],
            ["mention_tags.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.PrimaryKeyConstraint("tag_id", "mention_id"),
    )
    op.create_table(
        "tags_for_users",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("user_chat_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_chat_id", "user_id"],
            ["users.chat", "users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "user_chat_id", "tag_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tags_for_users")
    op.drop_table("mentions_for_tags")
    op.drop_table("tags")
    op.drop_table("mention_tags")
    # ### end Alembic commands ###
